### ISSUE TITLE
Nested regions in frontend

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#103]
In an effort to clean up the frontend and the data stores of PAVICS, @huard and I were wondering if it would be possible to create nested drop-downs of layers by grouping for the frontend UI. What does that mean? Well, this:

Current setup
```
Public
    MRC Regions
    Economic Regions
    Hydro Region Level 1
    Hydro Region Level 2
    Hydro Region Level 3
```

What would be better
```
Public
    Social Regions
        MRC
        Economic Zones
    Hydro
        Level 1
        Level 2
        Level 3
```

There is a way within GeoServer to assign layers to grouped categories with different methods of displaying them (e.g. `Single`, `Named Tree`, `Container Tree`, `Earth Observation Tree`) but when I try initializing a group, the frontend no longer displays any layers. I'm wondering why this is the behaviour and whether this is something that can be easily implemented. Is this a hidden feature? Is it available in newer instances of PAVICS? Clarifications welcome.

**Comment by Zeitsperre** [comment]
@Renaud009 Are you familiar with how the frontend region selections widget accesses the region layers?

**Comment by Renaud009** [comment]
Be aware that there are couple newer frontend image versions that haven't been deployed. What version of frontend/magpie/twitcher are you using?

Latest frontend version doesn't even show such hardcoded "Public" folder anymore since frontend regions list, at least in master branch, now shows a list of regions filtered by permissions. First, make sure geoserver workspaces are in magpie and that anonymous user (or any other current user) has access to these workspaces.

Older frontend was probably looping around the result of geoserver GetCapabilities, so maybe adjusting it could fix your problem.

**Comment by Zeitsperre** [comment]
Thanks for the clarifications @Renaud009 

I was able to play around with this a bit yesterday but I wasn't able to get this working on the newer instances of PAVICS at CRIM. I'll need to explore the Magpie permissions systems a bit more to see if such a feature is supported at the moment, or if it'll require more configurations within GeoServer etc.
