### ISSUE TITLE
Secure folder on THREDDS server is accessible through OPeNDAP

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#111]
There is a `/testdata/secure` folder on THREDDS that should require authentication. It is however possible at the moment to access it through DAP. 

See `docs/source/notebooks/pavics_thredds.ipynb`. 

## Requirements:
 - Changing permissions on dataset should not break client code (e.g. from private to public)
 - A dataset can be restricted for some groups but not others
 - Some dataset may have public metadata but private data

**Comment by fmigneault** [comment]
With current setup, since `anonymous` has access to top level `thredds` everything is open.
https://pavics.ouranos.ca/magpie/ui/groups/anonymous/thredds

We have 3 options: 
1. We replace top-level `thredds` access from `anonymous` to `administrators`.
    Then, for each sub-directory, we apply the appropriate `anonymous` permission.
    **Downside**: `thredds` is not directly browse-able anymore and we need to maintain access for every new directory added.
    **Advantage**: nothing new to implement.
2. We do the same as (1), but also *implement* `read-match`/`write-match` permissions to control access of direct resource instead of inherited permissions. This feature exists for `api` service-type but not `thredds`.
    **Downside**: still need to maintain access for every new directory added.
    **Advantage**: `thredds` direct access for `anonymous` can be allowed for browsing.
3. This `deny` feature https://github.com/Ouranosinc/Magpie/issues/235, which would explicitly deny access to the desired directory.
    **Downside**: major refactoring of Magpie permissions management, resolution, API and UI.
    **Advantage**: don't need to keep track of permissions for new directories.

**Comment by dbyrns** [comment]
4. move everything under a public directory but the secure stuff
    **Downside**: Require a specific data organisation
    **Advantage**: nothing new to implement, don't need to keep track of perms. for new directories.

**Comment by huard** [comment]
@dbyrns If we have folder 1 visible to group 1 and folder 2 visible to group 2, do we need to make sure folder 1 and 2 are within the same parent directory ?

**Comment by huard** [comment]
I think "THREDDS is not browse-able" is a problem. 
Could we restrict data access while granting anonymous access to metadata (and browsing) ?

**Comment by tlvu** [comment]
>     1. move everything under a public directory but the secure stuff
>        **Downside**: Require a specific data organisation
>        **Advantage**: nothing new to implement, don't need to keep track of perms. for new directories.

Yeah that's worth to explore as well.  Don't need to keep track of new dirs is a big plus.

However, not sure how the specific data organisation will impact our archiving.  If the same dataset is split under public and secure hierarchy, when comes the time to archive this dataset, we have to remember to archive both parts (some parts under public hierarchy, some parts under secure hierarchy).  I am thinking further than just the `testdata` hierarchy having split secure access.

We might also have more that just public vs authenticated users access.  Amongst the authenticated users, some users might have access to some secure folders while other might not.  Simply splitting the top hierarchy will not be flexible enough.

I think we should define all the possible use-cases/requirements first, then refactor accordingly.  We probably should not implement all the possible use-cases immediately but the initial refactor/re-design should allow gradual implementation without requiring another refactor/re-design.

**Comment by dbyrns** [comment]
I agree with tlvu that use-case first is the way to go. @huard the use case folder 1 visible to group1 and folder to group 2 is the exact situation currently supported by magpie. Magpie allow to give access to a specific subtree to some groups. But if both of them must see the parent directory then we fall into the not supported case which is to remove permissions of a specific subtree to some or all users. The catalog/solr was perfect for that because it returns all datasets filtered based on permissions. Howeever Thredds browsing capabilities does not fit well this use case because we need parent access to reach what we really have permission to and at some point someone will see a catalog with child folders for which it does not have access.

**Comment by huard** [comment]
Just to make sure I understand, this situation is not supported because level 0 permissions propagate downward ? 
- anonymous (0)
  - anonymous (1)
  - group1 (1)

**Comment by fmigneault** [comment]
@dbyrns 
>     4. move everything under a public directory but the secure stuff
>        **Downside**: Require a specific data organisation
>        **Advantage**: nothing new to implement, don't need to keep track of perms. for new directories.

This will still need option (2) in order to provide the `read-match` public access to top level in order to make the "landing page" of thredds browse-able.

@tlvu 
> We might also have more that just public vs authenticated users access. Amongst the authenticated users, some users might have access to some secure folders while other might not. Simply splitting the top hierarchy will not be flexible enough.

This should be possible if we make `secure` directory admin-only and add individually more permissive access to specific user/directory or user/file as required. The problem is the other way around when we want to restrict more an already more permissive resource.

@huard 
> Just to make sure I understand, this situation is not supported because level 0 permissions propagate downward ?
> 
>     * anonymous (0)
>       
>       * anonymous (1)
>       * group1 (1)

Yes.

**Comment by huard** [comment]
Ok. I think that's a problem, but I suggest we wait before making a decision. 

Here is my suggestion: 
1. Move the secure folder at the top level and test that case with notebooks. Close issue. 
2. Work on the virtual filesystem (NcML) and catalog 2.0. (this will take us into 2020)
3. Define use cases in tandem with new options offered by virtual fs and catalog. 
4. Decision on whether or not Magpie upgrade is necessary based on use cases.

**Comment by tlvu** [comment]
Possible fix in https://github.com/Ouranosinc/Magpie/issues/342
