### ISSUE TITLE
Customize THREDDS configuration

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#112]
We're using stock THREDDS config at the moment, but there are a number of options that would be worthwhile to experiment with. 

See https://www.unidata.ucar.edu/software/thredds/current/tds/reference/ThreddsConfigXMLFile.html#Server_Description

In particular, WMS and WCS services, logical aggregations and ncISO. 

```
ncISO supports three new services for datasets:

- NCML: an NcML representation of the dataset's structure and metadata;
- ISO: an ISO 19115 metadata representation of the dataset; and
- UDDC: an evaluation of how well the metadata contained in the dataset conforms to the NetCDF Attribute Convention for Data Discovery (NACDD) (also see the NOAA/NGDC page on NACDD).
```

**Comment by tlogan2000** [comment]
WCS via thredds would be great.  There is potential interest for various 'atlas' products from hydro members

**Comment by huard** [comment]
Also look at the config options for caching.

**Comment by huard** [comment]
Nciso, cache optimization, aggregations.

WMS and WCS are low priority. One thing we'll want to do later is benchmark tds WMS against ncwms2.

**Comment by tlvu** [comment]
WIP branch: https://github.com/Ouranosinc/PAVICS/tree/Customize-THREDDS-configuration-fix-112

ncISO enabled, not sure what to test to make sure it is working at intended.

Replace http://lvupavics.ouranos.ca with http://lvupavics-lvu.pagekite.me for outside of Ouranos access.

http://lvupavics.ouranos.ca/thredds/catalog/birdhouse/testdata/flyingpigeon/catalog.html?dataset=birdhouse/testdata/flyingpigeon/tmax.obs.nc

![2019-08-28-171911_888x647_scrot](https://user-images.githubusercontent.com/11966697/63877945-18dfdb00-c9b8-11e9-995f-0f94812c8d15.png)

NCML: http://lvupavics.ouranos.ca/twitcher/ows/proxy/thredds/ncml/birdhouse/testdata/flyingpigeon/tmax.obs.nc?catalog=http%3A%2F%2Flvupavics.ouranos.ca%3A8083%2Fthredds%2Fcatalog%2Fbirdhouse%2Ftestdata%2Fflyingpigeon%2Fcatalog.html&dataset=birdhouse%2Ftestdata%2Fflyingpigeon%2Ftmax.obs.nc

![2019-08-28-172221_888x648_scrot](https://user-images.githubusercontent.com/11966697/63878097-68bea200-c9b8-11e9-98b8-9fa2699d8547.png)

UDDC: http://lvupavics.ouranos.ca/twitcher/ows/proxy/thredds/uddc/birdhouse/testdata/flyingpigeon/tmax.obs.nc?catalog=http%3A%2F%2Flvupavics.ouranos.ca%3A8083%2Fthredds%2Fcatalog%2Fbirdhouse%2Ftestdata%2Fflyingpigeon%2Fcatalog.html&dataset=birdhouse%2Ftestdata%2Fflyingpigeon%2Ftmax.obs.nc

![2019-08-28-172342_889x647_scrot](https://user-images.githubusercontent.com/11966697/63878212-ac191080-c9b8-11e9-9e58-924dc96ca640.png)

ISO: http://lvupavics.ouranos.ca/twitcher/ows/proxy/thredds/iso/birdhouse/testdata/flyingpigeon/tmax.obs.nc?catalog=http%3A%2F%2Flvupavics.ouranos.ca%3A8083%2Fthredds%2Fcatalog%2Fbirdhouse%2Ftestdata%2Fflyingpigeon%2Fcatalog.html&dataset=birdhouse%2Ftestdata%2Fflyingpigeon%2Ftmax.obs.nc

![2019-08-28-172602_891x649_scrot](https://user-images.githubusercontent.com/11966697/63878332-ed112500-c9b8-11e9-8807-1004b3a51430.png)

**Comment by huard** [comment]
Ça a l'air de marcher ! 
On va vouloir que le UDDC score soit meilleur que ça pour les jeux de données qu'on héberge.

**Comment by tlvu** [comment]
WCS and WMS seems working, again I do not know how to test them properly.  The funny thing is they seems to have already been configured but not enabled !  Not sure why.

WMS link on a small file seems slow as well, not sure if it's because of pagekite.me or it's really slow.

Still trying to understand aggregation via NcML.  Correct me if it's a different kind of aggregation we want.

Different accesses enabled: https://lvupavics-lvu.pagekite.me/thredds/catalog/birdhouse/testdata/flyingpigeon/catalog.html?dataset=birdhouse/testdata/flyingpigeon/tmax.obs.nc

![2019-09-09-175254_870x647_scrot](https://user-images.githubusercontent.com/11966697/64554658-600c8b00-d32b-11e9-9c7e-cee0f7c92153.png)

WCS https://lvupavics-lvu.pagekite.me/twitcher/ows/proxy/thredds/wcs/birdhouse/testdata/flyingpigeon/tmax.obs.nc?service=WCS&version=1.0.0&request=GetCapabilities

![2019-09-09-175322_870x654_scrot](https://user-images.githubusercontent.com/11966697/64554690-70246a80-d32b-11e9-9cf8-840f849edd0b.png)

WMS: https://lvupavics-lvu.pagekite.me/twitcher/ows/proxy/thredds/wms/birdhouse/testdata/flyingpigeon/tmax.obs.nc?service=WMS&version=1.3.0&request=GetCapabilities

![2019-09-09-175359_813x640_scrot](https://user-images.githubusercontent.com/11966697/64554614-4a976100-d32b-11e9-98f5-9c286696542d.png)

**Comment by huard** [comment]
J'aimerais mieux comprendre comment l'aggrégation fonctionne. Est-ce qu'on peut aggréger CLIMEX par exemple, pour avoir un fichier logique qui comprend toutes les réalisations de l'ensemble ?

**Comment by tlvu** [comment]
Créer un fichier qui inclus les dimensions de plusieurs petits fichiers, c'est ce que je pense que agrégation par NcML nous  donne.

**Comment by tlvu** [comment]
Got a sample aggregation of all files from this folder https://lvupavics-lvu.pagekite.me/thredds/catalog/birdhouse/nrcan/nrcan_canada_daily/tasmin/catalog.html

Aggregated virtual dataset: https://lvupavics-lvu.pagekite.me/thredds/catalog.html?dataset=example-ncml-aggregation
![2019-09-10-150617_1023x600_scrot](https://user-images.githubusercontent.com/11966697/64642630-cbfafc00-d3dc-11e9-9487-67a603f4225c.png)

Test with sample notebook (thanks Travis for the xarray help)
![2019-09-10-150647_934x818_scrot](https://user-images.githubusercontent.com/11966697/64642644-d1f0dd00-d3dc-11e9-916a-9b7d3d32ba1d.png)

Working on how to create virtual folders to better organize those virtual datasets and how to make them reload/detect changes on disk.

**Comment by tlvu** [comment]
Found a better way of doing this.  Instead of modifying Thredds config, we can simply drop a `.ncml` file in the `birdhouse` folder hierarchy and that `.ncml` file will be treated like regular "aggregated" `.nc` file.

Advantage:
* Do not need to constantly modify and re-deploy Thredds config which force a restart of the Thredds server, this scale way better when we have hundreds of aggregations to maintain
* Do not need to create extra virtual hierarchy/catalog on Thredds to hold the virtual datasets
* The `.ncml` file stays next to the `.nc` files it aggregate/modify so things are centralized, easier to manage
* Anyone can download the `.ncml` file and see how the aggregation is actually coded and to audit for error, openness and transparency

Prototype:

Here is the `.ncml` file when browsing Thredds: http://lvupavics-lvu.pagekite.me/thredds/catalog/birdhouse/nrcan/nrcan_canada_daily/catalog.html

![2019-09-13-144643_949x554_scrot](https://user-images.githubusercontent.com/11966697/64887036-97ce4800-d635-11e9-9edd-392ec19b73a6.png)

All the subsetting services seems to work (I can only test opendap, the rest I don't know how to test)  on the `.ncml` file and the "HTTPServer" link gives you the raw `.ncml` to audit: http://lvupavics-lvu.pagekite.me/thredds/catalog/birdhouse/nrcan/nrcan_canada_daily/catalog.html?dataset=birdhouse/nrcan/nrcan_canada_daily/tasmin-agg.ncml

![2019-09-13-142656_935x730_scrot](https://user-images.githubusercontent.com/11966697/64886676-bbdd5980-d634-11e9-872a-f8e9950e9bc8.png)

Xarray is able to open the `.ncml` file as if it was a `.nc` file transparently:

![2019-09-13-141416_907x893_scrot](https://user-images.githubusercontent.com/11966697/64886720-d283b080-d634-11e9-8baf-08ce307b8d70.png)

**Comment by huard** [comment]
Bien joué ! Et côté performance ?

**Comment by tlvu** [comment]
Cote performance, 1ere impression, le `tasmin-agg.ncml` a l'air de prendre le meme temps que l'ancien virtual dataset cree par Thredds config lui-meme quand je roule dans le notebook.  Par contre, c'est juste 1 essaie, pas teste plusieurs fois et prendre une moyenne.

Meme avec une petite penalite de performance, avec les fichier `.ncml`, la gestion est tellement plus simple que je pense qu'ils valent quand meme la peine.
