### ISSUE TITLE
Synchronization with Birdhouse documentation

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#15]
As discussed at the workshop, it may be worthwhile to compare and push general updates/changes to the Birdhouse documentation so we can can streamline PAVICS-specific documentation and reduce redundancy. I'll be looking into this.

**Comment by huard** [comment]
http://fmarco76.github.io/git%20and%20related%20services/readthedocs/

**Comment by Zeitsperre** [comment]
Perfect! Am I correct in assuming that the base docs are here? https://github.com/bird-house/birdhouse-docs

**Comment by huard** [comment]
That's my understanding. The challenge will be to account for the overall birdhouse project, PAVICS specific stuff (pavics-sdi) and individual birds, which might differ in the live pavics server and the birdhouse repo. If you can find an elegant solution to this, it would be great.

**Comment by Zeitsperre** [comment]
No promises, but I'll see what I can do. It might make sense to somehow simply add the automated descriptions of the WPS services for each bird at the end of the docs. In any case, this will make documentation in the future much simpler.

**Comment by huard** [comment]
In that vein, note that the autoprocess directive scrapes the content of the class __doc__ and appends it to the auto-generated docs. This means we can add Notes, Refefences, See Also and Examples section. 
https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt
It may thus be simpler to put all the docs related to individual processes within the class docstring, and then use autoprocess to extract it, instead of writing independent rst files for the examples.
