### ISSUE TITLE
WFS support in notebooks

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#159]
# Use case
Inside a notebooks, a user wants to display polygons stored a WFS server on a map, click on one polygon and retrieve its contour and properties.

Given a layer `typename`, we want the canvas to display the features inside the displayed map. 

For example, see Raven notebook : https://github.com/Ouranosinc/raven/blob/master/docs/source/notebooks/Region_selection.ipynb

# How ?
Notebooks use the ipyleaflet to display maps. There are leafletJS plugins that support WFS: 
- [Leaflet-WFST](https://github.com/Flexberry/Leaflet-WFST)
- [azgs-leaflet](https://github.com/azgs/azgs-leaflet)

We would need to select a plugin and then write code in `ipyleaflet` to use this plugin: https://github.com/jupyter-widgets/ipyleaflet/issues/442

**Comment by f-PLT** [comment]
Alright, so I went through the relevant modules and plugins, and played around jupyter notebooks with ipyleaflet. Here’s my rundown:

**The plugins:**

Both azgs and Leaflet-WFS-T lack support. We could end up having to support our chosen plugin on top of it’s integration in ipyleaflet.

- azgs has not been updated in 8 years. Solo developer
- Leaflet-WFST was created by a group, but has been neglected in recent years. Mainly a single developer still maintaining it, barely, and is out of date with the current Leaflet version. Has been in beta versions since august 2017

*AZGS*
- WFS to geojson approach
- Simple but time since last update makes me expect it might need an update first
- Have yet to test it, but could be a good inspiration for port, either local or in ipyleaflet
- Limited to geojson for WFS formats, and non transactional

*Leaflet-WFST*
- Probably works out of the box with ipyleaflet since they share Leaflet versions for now
- More complex so could be longer to integrate with ipyleaflet
- Full transactional WFS
- If ipyleaflet updates their Leaflet version, could introduce breaking changes for plugin

Potentially a lot of work, now and down the line.

**Potential alternative:**

If I’m not mistaken, we are considering a read-only approach for the WFS, so we do not need transactional properties. 

Leaflet and ipyleaflet are already capable of using a geojson source. If considering the WFS geojson approach of AZGS, might as well build something tailored for our purposes.

It could be simpler to use the WFS to get the data in geojson format, which could then be fed to ipyleaflet, and even wrap it in a snippet or an API so it’s even easier for the end user.

Side bonus: One less dependency and our use of ipyleaflet is less dependent on it’s version.

**Comment by dbyrns** [comment]
Thank you @f-PLT. @huard, I got briefed by Francis already and would like to have your opinion on that. If you want, we could also have a call.

**Comment by huard** [comment]
Correct, this is read-only.

Do you mean basic read-only WFS support would be implemented directly in Leaflet and pyleaflet (without external plugins) ?

**Comment by f-PLT** [comment]
So, a quick recap and where we're at:

Leaflet.js : Doesn't support WFS natively. Two plugins do, but lack maintenance

The plugins: After a bit more research => They make a request to the WFS, transforms the response to layers/features that Leaflet.js understands. They can be used with a bbox approach, but overall they stay static. So it's the same WFS => geojson approach we talked about, but through javascript dependencies.

The WFS => geojson approach: Turns out, it's already implemented and documented right in Pavics : https://pavics-sdi.readthedocs.io/en/latest/notebooks/WFS_example.html

The wfs response can then be sent to ipyleaflet.GeoJSON and handled like any other vector source in ipyleaflet.

Seeing as there's an easy way with owslib to import from a WFS, I find there's little incentive to updating and maintaining javascript libraries that produce the same end result with far more effort.

From my test notebook:
```
from ipyleaflet import Map, GeoJSON
from owslib.wfs import WebFeatureService
import json

# Url
wfs_url = 'http://boreas.ouranos.ca/geoserver/wfs'

# Connect to GeoServer WFS service. 
wfs = WebFeatureService(wfs_url, version='2.0.0')

#--

# Fetch and prepare data
data = wfs.getfeature(typename='public:canada_admin_boundaries', bbox=(-74.5, 45.2, -73, 46), outputFormat='JSON')
geojson_data = json.loads(data.getvalue().decode())

#--

# Prepare map
m = Map(center=(54, -73.5), zoom=4)
geo_json = GeoJSON(data=geojson_data)
m.add_layer(geo_json)

# Show Map
m
```
From there, ipyleaflet already has components to create popups and displays from the information inside the geojson, but it has to be tailored to the specific layer.

This, added to the above, would display the name of the province after you click on it:

```
from ipywidgets import Text, HTML
from ipyleaflet import WidgetControl, GeoJSON 

html1 = HTML('''
    <h4>Province Name</h4>
    Click on a province state
''')
html1.layout.margin = '0px 20px 20px 20px'
control1 = WidgetControl(widget=html1, position='bottomright')

m.add_control(control1)

def update_html(feature, **kwargs):
    html1.value = '''
        <h4>Province Name</h4>
        <h4><b>{}</b></h4>
    '''.format(feature['properties']['PRENAME'])

geo_json.on_click(update_html)
```
So this brings us back to expectations. 

This would make for a quick solution, but I'm guessing you were looking for less input from the user. I talked with @dbyrns  and we're thinkings of a few ways we could improve it, but apart from a "boilerplate" notebook template or module, most of our alternatives look like major development efforts to Leaflet.js or it's plugins and then to ipyleaflet.

**Comment by huard** [comment]
Got it. Indeed, I would ideally like an API similar to WFSLayer, even if the implementation is in pure python. It could live in birdy for now. If we're happy with it, we can port it later to ipyleaflet.

**Comment by f-PLT** [comment]
I have a first prototype ready, will do a PR in birdy in a few moments.
