### ISSUE TITLE
Allow search for a set of available variables (logical AND)

### ISSUE THREAD

**Issue by bstdenis** [Ouranosinc/pavics-sdi#26]
The ESGF search only supports logical AND for different facets, and multiple entries for the same facet (e.g. multiple variables) are combined as logical OR (unless they are != restriction, in which case it reverts back to a logical AND).

Once we have the result from the solr search, we would need to go through that json structure and remove entries that do not satisfy our logical AND. This also require an additional syntax in the inputs, perhaps constraints=model:MRCC5,variable+:pr,variable+:tas could be implemented?

**Comment by huard** [comment]
I "think" it is possible to do AND operations using the free text query with labels, ie
`https://esgf-data.dkrz.de/esg-search/search?experiment=rcp26&query=variable:tas AND variable:pr`
returns results, while 
`https://esgf-data.dkrz.de/esg-search/search?experiment=rcp26&query=variable:tas AND variable:sic`
returns nothing, I suppose because the "dataset" is different, since tas and sic are in different realms.

Let me know if I'm correct. 
That would partially solve the issue, but would not work for variables from the same simulation stored in different realms. Maybe this could be solved using the id based search.

**Comment by bstdenis** [comment]
Yes, that works as you describe. However we can't use the same search query to retrieve the file urls (type=File) since the file entries only contain their specific variable (as opposed to the dataset entry which contain the list of variables). So the file search would have to be a two step process:

1. Dataset search with the free query logical AND syntax
2. File search constrained by the previously found dataset_id.

This still does not solve the variables in different realms problem, I don't know how to do that in Solr. One thing to consider: https://wiki.apache.org/solr/Join

**Comment by huard** [comment]
Interesting ! I'll ask someone from ESGF about our "same simulation different realms" question.
