### ISSUE TITLE
Bad Gateway error

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#93]
When hitting flyingpigeon through the proxy, I irregularly but often get Bad Gateway errors; 
Try for example `https://pavics.ouranos.ca/twitcher/ows/proxy/flyingpigeon/wps`

Could this be due to the proxy server, cause flyingpigeon seems to be up and running.

**Comment by tomLandry** [comment]
@huard In the next few hours, I'll do a second pass in https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues backlog and hopefully TODO. These critical PAVICS issues should all get there somehow. Stay tuned, and know I'll be filtering mostly by critical and blocker.

**Comment by huard** [comment]
No, not sure. I'll check.

**Comment by fmigneault** [comment]
On my side, I receive 200 OK on `https://pavics.ouranos.ca/twitcher/ows/proxy/flyingpigeon/wps?service=wps&request=getcapabilities` with the expected `GetCapapibilities` XML response. 
Added the `getcapabilities` permission to myself on magpie.
Is the service accessed different for you? I cannot reproduce the Bad Gateway.

**Comment by dbyrns** [comment]
I think that @tlvu could be helpful here since he is setupping a test platform. With a minimum of load this issue could be well documented in no time. Since Finch is using the same architecture we must be able to reproduce and fix that.

**Comment by tlvu** [comment]
Not sure we are talking about the same thing, but I also notice this random error in a jupyter notebook:

```
from owslib.wps import WebProcessingService
wpsURL = 'https://boreas.ouranos.ca/twitcher/ows/proxy/flyingpigeon/wps'
wpsFP = WebProcessingService(wpsURL)

 File "<string>", line 6
XMLSyntaxError: Opening and ending tag mismatch: hr line 5 and body, line 6, column 8
```

Run the same code again in a minute and it works.  But if I do not give it some time to cool down, the error keeps coming back.

**Comment by dbyrns** [comment]
Not sure either if this is related but we saw in the past an error about malformed xml because twitcher was returning an uncompressed xml file using the same header of the proxied response which could have been compressed. This result in a partial document chopped after the size of the original compressed response. We have fix that by requesting uncompressed format to wps.

**Comment by huard** [comment]
@dbyrns @tlvu @tlogan2000 
We're having bad gateway issues with Finch as well, not just FP. I'll have to use CRIM's Finch instance for our demo, since ours seems to be broken. 

The plan that we agreed on is that CRIM will spend a couple of days a week over the next months to bring the PAVICS deployment back in sync again. I'm concerned this means we're going to have a non-functional production server for a couple of months. Would it make sense to do the work in this order: 
1. drop support for the UI on boreas
2. update twitcher
3. update magpie
4. update the UI
5. add support to the UI on boreas.

If 4 is the big chunk of work, then we get a functional public backend as soon as 2 is completed, which I expect to be a lot easier and quicker, right ? Does that make sense ? There would still be a UI running at CRIM which we could use as a demo if needed.

**Comment by dbyrns** [comment]
2 and 3 are already in process, 4 is planned in june/july given Félix availability so it's almost aligned with your schedule. In the meantime, if you want to proceed with 1 it's up to you. If the UI cannot bring anything in its current state then it could make sense.

**Comment by tlvu** [comment]
@huard I have a develop branch (newer twitcher than branch master but not latest) on my machine.

This seem to be working for me at the moment `curl --insecur "https://lvu.ouranos.ca/twitcher/ows/proxy/finch/wps?service=WPS&version=1.0.0&request=GetCapabilities"`.  Do you want to try to see if finch is working better on that develop branch?

If you have some finch notebooks, I can try them myself as well against that develop branch.

**Comment by huard** [comment]
Excellent ! Yes, here is a PR for a basic usage notebook: https://github.com/bird-house/finch/pull/29

**Comment by davidcaron** [comment]
FYI, between 10:30 and 12:00 I was doing intermittent updates on finch... sorry about that, there is a good chance the 502 were caused by that. Bad timing...

If there is anything I can do to help with this issue, let me know.

**Comment by huard** [comment]
The gateway errors were on Boreas. finch.crim.ca works like a charm.

**Comment by tlvu** [comment]
@huard ran the bird-house/finch#29 against my machine (develop branch), the output is here: https://gist.github.com/tlvu/4877d2eeefc47122e39dfa5a928c7bbb

It's not working probably due to config problem.  The url the server returned is:
`output_netcdf='http://localhost:5000/outputs/62f72bec-75aa-11e9-81be-0242ac19000f/out.nc'`
which is different from the original notebook:
`output_netcdf='https://finch.crim.ca/outputs/af7ce34a-75a4-11e9-a753-0242ac150005/out.nc'`

After this difference, nothing works anymore.

**Comment by huard** [comment]
Looking good, because the bad gateway error would have created problems before that. 
The difference in file name is expected, as pywps creates temporary directories to store outputs from requests. We could remove that from the notebook to avoid errors, but I think it's useful to show. 

The notebook is saving local copies of the output files in `/tmp`. Is your notebook server ok with this ?

**Comment by tlvu** [comment]
I see the output file in /tmp of my finch container:
```
$ docker exec -it finch bash
(base) root@b7fb769b2460:/code# cd /tmp
(base) root@b7fb769b2460:/tmp# ls
62f72bec-75aa-11e9-81be-0242ac19000f
(base) root@b7fb769b2460:/tmp# cd 62f72bec-75aa-11e9-81be-0242ac19000f/
(base) root@b7fb769b2460:/tmp/62f72bec-75aa-11e9-81be-0242ac19000f# ls -l
total 13
-rw-r--r-- 1 root root   362 May 13 18:10 log.txt
-rw-r--r-- 1 root root 25005 May 13 18:10 out.nc
(base) root@b7fb769b2460:/tmp/62f72bec-75aa-11e9-81be-0242ac19000f#
```

The different that bothers me is the `localhost:5000` vs `finch.crim.ca`.

**Comment by huard** [comment]
The regex you're doing doesn't catch it ?

**Comment by tlvu** [comment]
What regex?  The one Jenkins does to "alter" pavics.ouranos.ca host?  I am not running under Jenkins.  I am just running it by hand in the same docker image that Jenkins would run.

I think I might understand why.  The notebook server is unable to download the out.nc file since the url is `http://localhost:5000/outputs/...`.  It should have been `https://lvu.ouranos.ca/outputs/...`, like `https://finch.crim.ca/outputs/...`.  The finch server is reporting it's own url wrong.

**Comment by davidcaron** [comment]
I think it might come from the pywps `.cfg` file... check in the `[server]` section, the `outputurl` parameter should be `https://lvu.ouranos.ca/outputs` depending on how you configured static files to be served.

**Comment by tlvu** [comment]
I see 2 possible problems with finch config on Ouranos side:

* It looks like finch is writing the out.nc file to the wrong location (`/tmp/62f72bec-75aa-11e9-81be-0242ac19000f/out.nc`)

All the other birds, including finch, have this kind of volume mount in the docker-compose file:
```
volumes:
  - wps_outputs:/opt/birdhouse/var/lib/pywps/outputs
```
Finch should have written to `/opt/birdhouse/var/lib/pywps/outputs/62f72bec-75aa-11e9-81be-0242ac19000f/out.nc` then a link like `https://HOSTNAME/outputs/62f72bec-75aa-11e9-81be-0242ac19000f/out.nc` would have worked.

I do not know how to tell finch to write to `/opt/birdhouse/var/lib/pywps` instead of `/tmp`.

* Like @davidcaron said, somewhere in finch config, it should be configured to report its output url to be the public url of the proxy, not `localhost:5000`.

Is there a list of all the possible configurations options for finch?

**Comment by huard** [comment]
https://pywps.readthedocs.io/en/master/configuration.html

**Comment by tlvu** [comment]
This is odd, according to that pywps configuration help page, the 2 following configs seems to be what I need:
* outputpath: server path where to store output files.
* outputurl: corresponding URL

But none of the existing birds are using them in the PAVICS repo !

Are there configuration somewhere else than in the PAVICS repo?

**Comment by tlvu** [comment]
@davidcaron: Could you give me the pywps config file that the CRIM is using with Finch and the docker-compose section of Finch?

**Comment by davidcaron** [comment]
wps.cfg
```
...
[server]
url = https://192.168.99.201/wps
outputurl = https://192.168.99.201/outputs
outputpath = /data/wpsoutputs
...
```
nginx conf
```
...
    location /wps {
        proxy_pass http://finch:5001;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /outputs {
        alias /data/wpsoutputs;
    }
...
```
docker-compose.yml
```
  finch:
    image: ...
    container_name: finch
    command: ["gunicorn", "--config", "/code/gunicorn.py", "finch.wsgi:application"]
    environment:
      - PYWPS_CFG=/wps.cfg
    volumes:
      - ./config/finch/gunicorn.py:/code/gunicorn.py
      - ./config/finch/wps.cfg:/wps.cfg
      - wpsoutputs:/data/wpsoutputs
    restart: always
```

**Comment by tlvu** [comment]
@davidcaron your wps.cfg works, thanks.

I now have a different error, related to SSL verification since I use a self-signed certificate on my machine.  I did use `wps = WPSClient(url, verify=False)` but still have this error:

![2019-05-21-SSL-verify-error-with-birdy](https://user-images.githubusercontent.com/11966697/58127493-7b6c5280-7be3-11e9-8490-05dfc1c77383.png)

Is this a known self-signed SSL certificate support bug with the birdy library?

**Comment by davidcaron** [comment]
As far as I know, `verify=False` should do the job... My guess is that it passes the `verify=False` argument when executing requests, but not when retrieving outputs.

**Comment by huard** [comment]
This is an easy fix I think. Looking into it.

**Comment by huard** [comment]
https://github.com/bird-house/birdy/pull/123

**Comment by huard** [comment]
Is it possible that those bad gateway errors occur with POST requests ?

**Comment by dbyrns** [comment]
So you still are struggling with this issue? where are you in term of upgrade to the latest magpie/twticher version?

**Comment by tlvu** [comment]
We are trying Magpie/Twitcher upgrade this week, right after I am able to expose my test VM to the internet so I can show you guys if I encounter problem (the PR you approved, thx).

**Comment by tlvu** [comment]
Unrelated but I have to note it here else I keep forgetting about it.  FP Max connection bug is https://github.com/geopython/pywps/issues/448.  FP repo is read-only so can not open a new issue there, sorry for hijacking this issue.

It's on a same level of pain.  Either Bad Gateway error or Max Connection reached, both prevent FP to execute.

**Comment by huard** [comment]
Ok, here is a recap of what I, now, understand. 

I *think* this issue was fixed by @ldperron here: https://github.com/Ouranosinc/pywps/commit/203ae6dc83f46d783852a3b72b693a5d2301f453

This change has been pushed upstream in pywps: https://github.com/geopython/pywps/pull/341, so it is part of the 4.2 release. 

However, it seems that the environment in the flyingpigeon running on boreas (pavics-0.4.3) has pywps tagged at 4.0.0 in  `environment.yml`. 

I'd appreciate if someone could confirm this, as it would mean that our problem is already fixed, it's just not deployed...

**Comment by huard** [comment]
My suggestion would then be:
* Rename current FP to flyingpigeon_deprecated in docker_compose and canarie-api. 
* Cut a new FP release with the latest fixes
* Create new FP docker image with the latest FP release and add to compose
* Update notebooks to reflect any change.  
* Deploy 
* Move canarie-api subset service to new FP. 
* Remove deprecated FP on Sept 9th

**Comment by ldperron** [comment]
I just checked directly on Boreas, the commit https://github.com/Ouranosinc/pywps/commit/203ae6dc83f46d783852a3b72b693a5d2301f453 is already there for flyingpigeon. I believe that flyingpigeon was built using pywps fork directly, not the upstream

**Comment by huard** [comment]
You're right. The Dockerfile includes 
```
RUN /opt/conda/envs/flyingpigeon/bin/pip install --upgrade git+https://github.com/Ouranosinc/pywps.git@pavics
```
